import {GameState,Edge,Player,validMoves,makeMove,completedBy,clone,boxEdges} from './engine';
export type Difficulty='easy'|'medium'|'hard'|'master';
const rng=(a:Edge[])=>a[Math.floor(Math.random()*a.length)];
const captures=(s:GameState)=>validMoves(s).filter(e=>completedBy(s,e).length>0);
function danger(s:GameState,e:Edge){const r=makeMove(s,e);if(!r)return 99;return captures(r.state).reduce((n,m)=>n+completedBy(r.state,m).length,0)}
function heuristic(s:GameState, ai:Player){const their=ai===0?1:0; let v=(s.scores[ai]-s.scores[their])*100; const cs=captures(s); if(s.current===ai)v+=cs.length*12;else v-=cs.length*12; for(let i=0;i<s.boxes.length;i++)if(s.boxes[i]===null){const sides=boxEdges(s.size,i).filter(x=>s.edges.has(x)).length; if(sides===2)v+=s.current===ai?-2:2;} return v;}
function key(s:GameState,d:number){return `${d}|${s.current}|${[...s.edges].sort().join(',')}`}
function search(s:GameState,ai:Player,depth:number,alpha:number,beta:number,memo:Map<string,number>):number{if(depth===0||s.status==='over')return heuristic(s,ai);const k=key(s,depth),old=memo.get(k);if(old!==undefined)return old;const max=s.current===ai;let best=max?-Infinity:Infinity;for(const m of ordered(s)){const n=makeMove(s,m)!.state;const x=search(n,ai,depth-1,alpha,beta,memo);if(max){best=Math.max(best,x);alpha=Math.max(alpha,best)}else{best=Math.min(best,x);beta=Math.min(beta,best)}if(beta<=alpha)break;}memo.set(k,best);return best}
function ordered(s:GameState){return validMoves(s).sort((a,b)=>completedBy(s,b).length-completedBy(s,a).length||danger(s,a)-danger(s,b));}
export function aiMove(s:GameState,d:Difficulty):{move:Edge; reason:string}{const moves=validMoves(s), caps=captures(s);if(d==='easy'){const pool=caps.length&&Math.random()<.55?caps:moves;return{move:rng(pool),reason:caps.length?'A capture was available.':'Exploring an open route.'}} if(d==='medium'){const safe=moves.filter(m=>danger(s,m)===0);const pick=caps[0]??rng(safe.length?safe:moves);return{move:pick,reason:caps.length?'Completes a box immediately.':safe.length?'Avoids an immediate capture.':'No safe edge remains.'}}const depth=d==='master'?(s.size<=4?12:s.size<=5?8:5):(s.size<=4?6:4);let best=ordered(s)[0],value=-Infinity,memo=new Map<string,number>();for(const m of ordered(s)){const n=makeMove(clone(s),m)!.state;const score=search(n,s.current,depth-1,-Infinity,Infinity,memo);if(score>value){value=score;best=m;}}return{move:best,reason:caps.length?'Converts a forced capture sequence.':'Search selected the safest chain position.'}}
