import './style.css';
import './fixes.css';
import {initGame,makeMove,GameState,Player,Edge,winner,validMoves} from './engine';
import {aiMove,Difficulty} from './ai';

type Mode='ai'|'pvp'; type Settings={size:number; difficulty:Difficulty; sound:boolean; animations:boolean; glow:string; theme:string; p1:string;p2:string};
const saved=localStorage.getItem('db-settings');
let settings:Settings=saved?JSON.parse(saved):{size:5,difficulty:'medium',sound:true,animations:true,glow:'100',theme:'cyber',p1:'PLAYER 1',p2:'AI'};
let state:GameState=initGame(settings.size),mode:Mode='ai',screen:'menu'|'game'|'settings'|'stats'='menu',thinking=false,paused=false,lastReason='',timer:number|undefined;
type Stats={played:number;won:number;lost:number;draws:number;boxes:number;best:number;streak:number;longest:number;seconds:number;sizes:Record<string,number>};
let stats:Stats=JSON.parse(localStorage.getItem('db-stats')||'{"played":0,"won":0,"lost":0,"draws":0,"boxes":0,"best":0,"streak":0,"longest":0,"seconds":0,"sizes":{}}');
const app=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:string)=>s.replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]!));
const opponent=()=>mode==='ai'?settings.p2:(settings.p2==='AI'?'PLAYER 2':settings.p2);
const pname=(p:Player)=>p===0?settings.p1:opponent();
function persist(){localStorage.setItem('db-settings',JSON.stringify(settings));localStorage.setItem('db-stats',JSON.stringify(stats));}
function sound(freq=360,d=.05){if(!settings.sound)return;const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function fmt(sec:number){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function start(m:Mode){mode=m;state=initGame(settings.size);screen='game';paused=false;lastReason='';clearInterval(timer);timer=window.setInterval(()=>{if(screen==='game'&&!paused&&state.status==='playing')render()},1000);render();}
function move(e:Edge){if(thinking||paused||state.status==='over'||(mode==='ai'&&state.current===1))return;const x=makeMove(state,e);if(!x)return;state=x.state;sound(x.captured.length?620:330,.08);render();if(state.status==='over')finish();else if(mode==='ai'&&state.current===1)window.setTimeout(aiTurn,420)}
function aiTurn(){if(mode!=='ai'||state.current!==1||state.status!=='playing'||paused)return;thinking=true;render();window.setTimeout(()=>{const r=aiMove(state,settings.difficulty);lastReason=r.reason;const x=makeMove(state,r.move);if(x)state=x.state;thinking=false;sound(x?.captured.length?560:270,.08);render();if(state.status==='over')finish();else if(state.current===1)window.setTimeout(aiTurn,340)},250)}
function finish(){clearInterval(timer);const w=winner(state),secs=Math.floor((Date.now()-state.startedAt)/1000);stats.played++;stats.boxes+=state.scores[0];stats.best=Math.max(stats.best,state.scores[0]);stats.seconds+=secs;stats.sizes[state.size]=(stats.sizes[state.size]||0)+1;if(w===null){stats.draws++;stats.streak=0}else if(w===0){stats.won++;stats.streak++;stats.longest=Math.max(stats.longest,stats.streak)}else{stats.lost++;stats.streak=0}persist();sound(w===0?760:210,.2);render();}
function board(){const n=state.size, pad=9, step=82, len=(n-1)*step+pad*2;let shapes=''; for(let i=0;i<state.boxes.length;i++){const p=state.boxes[i];if(p!==null){const r=Math.floor(i/(n-1)),c=i%(n-1);shapes+=`<rect class="box p${p}" x="${pad+c*step+7}" y="${pad+r*step+7}" width="${step-14}" height="${step-14}" rx="8"/><text class="box-label" x="${pad+c*step+step/2}" y="${pad+r*step+step*.59}">${pname(p).slice(0,2)}</text>`}}
 for(const e of validMoves(state)){const x1=pad+e.c*step,y1=pad+e.r*step,x2=e.dir==='h'?x1+step:x1,y2=e.dir==='v'?y1+step:y1;shapes+=`<line data-edge="${e.id}" class="edge target" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`}
 for(const id of state.edges){const [dir,rest]=[id[0],id.slice(1)], [r,c]=rest.split(':').map(Number),e:{dir:'h'|'v';r:number;c:number}={dir:dir as 'h'|'v',r,c}, owner=state.moves.find(m=>m.edge.id===id)?.player??0,x1=pad+c*step,y1=pad+r*step,x2=e.dir==='h'?x1+step:x1,y2=e.dir==='v'?y1+step:y1;shapes+=`<line class="edge locked p${owner}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`}
 for(let r=0;r<n;r++)for(let c=0;c<n;c++)shapes+=`<circle class="dot" cx="${pad+c*step}" cy="${pad+r*step}" r="5"/>`;
 return `<svg id="board" viewBox="0 0 ${len} ${len}" role="application" aria-label="Dots and Boxes board. Select a glowing edge to place a line.">${shapes}</svg>`}
function game(){const total=(state.size-1)**2, secs=Math.floor((Date.now()-state.startedAt)/1000), turn=state.status==='over'?'FINAL RESULT':thinking?'AI IS THINKING…':paused?'GAME PAUSED':`CURRENT TURN: ${pname(state.current)}`;return `<main class="game-shell"><header class="topbar"><button class="brand" data-action="menu">DOTS <i>//</i> BOXES</button><div class="scorecards"><section class="score p0"><b>${esc(settings.p1)}</b><strong>${String(state.scores[0]).padStart(2,'0')}</strong></section><em>VS</em><section class="score p1"><b>${esc(opponent())}</b><strong>${String(state.scores[1]).padStart(2,'0')}</strong></section></div><div class="head-actions"><button aria-label="Toggle sound" data-action="sound">${settings.sound?'◉':'○'}</button><button data-action="menu">EXIT</button></div></header><section class="turn ${thinking?'thinking':''}">${turn}</section><div class="play-area"><aside class="intel"><h3>GAME TELEMETRY</h3><dl><div><dt>TURN</dt><dd>${pname(state.current)}</dd></div><div><dt>BOXES REMAINING</dt><dd>${total-state.scores[0]-state.scores[1]}</dd></div><div><dt>MOVES</dt><dd>${state.moves.length}</dd></div><div><dt>GAME TIME</dt><dd>${fmt(secs)}</dd></div></dl><p class="reason">${lastReason?`AI: ${lastReason}`:'Connect nodes. Claim sectors.'}</p><div class="history">${state.moves.slice(-5).reverse().map((m,i)=>`<p>#${state.moves.length-i} — ${esc(pname(m.player))}<small>${m.captured.length?`Captured ${m.captured.length} box${m.captured.length>1?'es':''}`:'Linked edge'}</small></p>`).join('')||'<p>No moves recorded.</p>'}</div></aside><div class="board-wrap ${paused?'paused':''}">${board()}${paused?'<div class="pause-card">PAUSED<br><button data-action="pause">RESUME</button></div>':''}</div><aside class="controls"><button data-action="pause">${paused?'RESUME':'PAUSE'}</button><button data-action="undo" ${mode==='ai'||state.moves.length===0?'disabled':''}>UNDO</button><button data-action="restart">RESTART</button><button data-action="fullscreen">FULLSCREEN</button><p>SIZE <b>${state.size}×${state.size}</b><br>MODE <b>${mode==='ai'?settings.difficulty.toUpperCase():'LOCAL'}</b></p></aside></div>${state.status==='over'?result(secs):''}</main>`}
function result(secs:number){const w=winner(state),title=w===null?'DRAW':`${pname(w)} WINS`;return `<div class="modal"><div class="result"><span>TRANSMISSION COMPLETE</span><h1>GAME OVER</h1><h2>${esc(title)}</h2><div class="final-score"><b>${state.scores[0]}</b><i>—</i><b>${state.scores[1]}</b></div><p>${state.moves.length} MOVES · ${fmt(secs)} · ${state.scores[0]+state.scores[1]} SECTORS CLAIMED</p><div class="modal-buttons"><button data-action="again">PLAY AGAIN</button><button data-action="menu">MAIN MENU</button></div></div></div>`}
function menu(){return `<main class="landing"><div class="status">SYSTEM ONLINE <i>●</i></div><div class="hero"><p class="eyebrow">TACTICAL GRID PROTOCOL // 01</p><h1>DOTS<span>//</span>BOXES</h1><p class="tagline">CONNECT. CAPTURE. CONQUER.</p><div class="menu-actions"><button data-action="vsai">VS COMPUTER <small>STRATEGIC AI</small></button><button data-action="vspvp">PLAYER VS PLAYER <small>LOCAL DUAL</small></button></div><div class="under-actions"><button data-action="how">HOW TO PLAY</button><button data-action="settings">SETTINGS</button><button data-action="stats">STATISTICS</button></div></div><footer>© 2086 GRID SYSTEMS <span>●</span> ALL SYSTEMS NOMINAL</footer></main>`}
function settingsView(){const sizes=[3,4,5,6,7].map(n=>`<button class="choice ${settings.size===n?'selected':''}" data-size="${n}">${n}×${n}</button>`).join('');return `<main class="panel-page"><button class="back" data-action="menu">← MAIN MENU</button><h1>SETTINGS <i>//</i> CONTROL</h1><div class="settings-grid"><section><h3>BOARD SIZE</h3><div class="choices">${sizes}</div><h3>AI DIFFICULTY</h3><div class="choices">${(['easy','medium','hard','master'] as Difficulty[]).map(x=>`<button class="choice ${settings.difficulty===x?'selected':''}" data-difficulty="${x}">${x.toUpperCase()}</button>`).join('')}</div><h3>PLAYER IDENTITIES</h3><label>PLAYER 1<input id="p1" value="${esc(settings.p1)}" maxlength="16"></label><label>PLAYER 2<input id="p2" value="${esc(settings.p2)}" maxlength="16"></label></section><section><h3>INTERFACE</h3><label class="toggle">SOUND EFFECTS <input type="checkbox" data-setting="sound" ${settings.sound?'checked':''}><span></span></label><label class="toggle">ANIMATIONS <input type="checkbox" data-setting="animations" ${settings.animations?'checked':''}><span></span></label><label>GLOW INTENSITY<input type="range" min="40" max="160" value="${settings.glow}" data-setting="glow"></label><h3>THEME</h3><div class="choices">${['cyber','matrix','neon','terminal'].map(x=>`<button class="choice ${settings.theme===x?'selected':''}" data-theme="${x}">${x.toUpperCase()}</button>`).join('')}</div></section></div></main>`}
function statsView(){const rate=stats.played?Math.round(stats.won/stats.played*100):0,avg=stats.played?fmt(Math.round(stats.seconds/stats.played)):'00:00';return `<main class="panel-page"><button class="back" data-action="menu">← MAIN MENU</button><h1>PLAYER <i>//</i> ARCHIVE</h1><div class="stat-grid">${[['GAMES PLAYED',stats.played],['VICTORIES',stats.won],['DEFEATS',stats.lost],['DRAWS',stats.draws],['WIN RATE',rate+'%'],['BOXES CAPTURED',stats.boxes],['BEST SCORE',stats.best],['LONGEST STREAK',stats.longest],['AVG. DURATION',avg]].map(x=>`<section><span>${x[0]}</span><b>${x[1]}</b></section>`).join('')}</div></main>`}
function render(){document.documentElement.dataset.theme=settings.theme;document.documentElement.style.setProperty('--glow',settings.glow+'%');app.innerHTML=screen==='menu'?menu():screen==='settings'?settingsView():screen==='stats'?statsView():game();}
app.addEventListener('click',ev=>{const t=(ev.target as HTMLElement).closest<HTMLElement>('[data-action],[data-edge],[data-size],[data-difficulty],[data-theme]');if(!t)return;if(t.dataset.edge){const id=t.dataset.edge!, e=validMoves(state).find(x=>x.id===id);if(e)move(e);return}if(t.dataset.size){settings.size=+t.dataset.size;persist();render();return}if(t.dataset.difficulty){settings.difficulty=t.dataset.difficulty as Difficulty;persist();render();return}if(t.dataset.theme){settings.theme=t.dataset.theme;persist();render();return}const a=t.dataset.action;if(a==='vsai')start('ai');if(a==='vspvp')start('pvp');if(a==='menu'){clearInterval(timer);screen='menu';render()}if(a==='settings'){screen='settings';render()}if(a==='stats'){screen='stats';render()}if(a==='sound'){settings.sound=!settings.sound;persist();render()}if(a==='pause'){paused=!paused;render()}if(a==='restart')start(mode);if(a==='again')start(mode);if(a==='undo'&&mode==='pvp'&&state.moves.length){const moves=state.moves.slice(0,-1);state=initGame(settings.size);for(const m of moves)state=makeMove(state,m.edge)!.state;render()}if(a==='fullscreen')document.documentElement.requestFullscreen?.();if(a==='how')alert('Select a glowing edge to connect adjacent dots. Complete the fourth side of a sector to claim it and take another turn. The player with the most sectors wins.');});
app.addEventListener('change',ev=>{const i=ev.target as HTMLInputElement;if(i.dataset.setting==='sound')settings.sound=i.checked;if(i.dataset.setting==='animations')settings.animations=i.checked;if(i.dataset.setting==='glow')settings.glow=i.value;if(i.id==='p1')settings.p1=i.value||'PLAYER 1';if(i.id==='p2')settings.p2=i.value|| (mode==='ai'?'AI':'PLAYER 2');persist();render()});
render();
